### PR TITLE
Fix compilation on OS X

### LINKED ISSUE #16: Cannot compile on OS X 10.14.2
Compilation dies here:

_make[2]: Entering directory `/opt/local/var/macports/build/_Users_alien_ports_emulators_opencbm/opencbm/work/code/xu1541/lib'
cc -I/opt/local/include -I/opt/local/include/ -g -Wall -pedantic -I../include/   -c -o close.o close.c
In file included from close.c:1:
../include/xu1541lib.h:57:8: error: unknown type name 'libusb_device_handle'
extern libusb_device_handle * xu1541lib_find(void);
       ^
../include/xu1541lib.h:58:8: error: unknown type name 'libusb_device_handle'
extern libusb_device_handle * xu1541lib_find_in_bootmode(unsigned int *p_soft_bootloader_mode);
       ^
../include/xu1541lib.h:59:47: error: unknown type name 'libusb_device_handle'
extern void                   xu1541lib_close(libusb_device_handle *handle);
                                              ^
../include/xu1541lib.h:60:57: error: unknown type name 'libusb_device_handle'
extern int                    xu1541lib_get_device_info(libusb_device_handle *handle, xu1541_device_info_t *device_info, unsigned int device_info_length);
                                                        ^
../include/xu1541lib.h:61:61: error: unknown type name 'libusb_device_handle'
extern void                   xu1541lib_display_device_info(libusb_device_handle *handle);
                                                            ^
../include/xu1541lib.h:62:63: error: unknown type name 'libusb_device_handle'
extern int                    xu1541lib_is_in_bootloader_mode(libusb_device_handle *handle);
                                                              ^
../include/xu1541lib.h:63:46: error: unknown type name 'libusb_device_handle'
extern void                   xu1541lib_wait(libusb_device_handle *handle);
                                             ^
../include/xu1541lib.h:64:58: error: unknown type name 'libusb_device_handle'
extern int                    xu1541lib_set_to_boot_mode(libusb_device_handle *handle);
                                                         ^
../include/xu1541lib.h:65:54: error: unknown type name 'libusb_device_handle'
extern int                    xu1541lib_get_pagesize(libusb_device_handle *handle);
                                                     ^
close.c:9:22: error: unknown type name 'libusb_device_handle'
void xu1541lib_close(libusb_device_handle *handle) {
                     ^
close.c:11:13: warning: implicit declaration of function 'libusb_release_interface' is invalid in C99 [-Wimplicit-function-declaration]
  int ret = libusb_release_interface(handle, 0);
            ^
close.c:12:14: error: use of undeclared identifier 'LIBUSB_SUCCESS'
  if (ret != LIBUSB_SUCCESS) {
             ^
close.c:13:40: warning: implicit declaration of function 'libusb_error_name' is invalid in C99 [-Wimplicit-function-declaration]
    fprintf(stderr, "USB error: %s\n", libusb_error_name(ret));
                                       ^
close.c:13:40: warning: format specifies type 'char *' but the argument has type 'int' [-Wformat]
    fprintf(stderr, "USB error: %s\n", libusb_error_name(ret));
                                ~~     ^~~~~~~~~~~~~~~~~~~~~~
                                %d
close.c:17:3: warning: implicit declaration of function 'libusb_close' is invalid in C99 [-Wimplicit-function-declaration]
  libusb_close(handle);
  ^
4 warnings and 11 errors generated._

The issue has to do something with the fact that wrong/no headers are included.

"libusb_device_handle" function is found in "/opt/local/include/libusb-1.0/libusb.h" but NOT in "/opt/local/include/usb.h"

As you can see "cc..." is totally missing the -DHAVE_LIBUSB=1 -DHAVE_LIBUSB1=1 -DHAVE_LIBUSB_1_0=1 stuff....thus "../include/xu1541lib.h" does not include anything:

#if HAVE_LIBUSB0
#include <usb.h>
#elif HAVE_LIBUSB1
#include <libusb.h>
#endif

### PR DESCRIPTION
**Pull request by bodgit**
There was still a condition for Darwin to use the old `libusb-config`, instead let it fall through to the catch-all condition which relies on `pkg-config` instead.

Also update the `Portfile` with the correct dependencies.

Fixes #16 

(this also probably supersedes #18 too)

### CODE REVIEW

**Comment by lafiosca** [comment]
I believe there is a small flaw in this Portfile. It seems that having two separate `depends_build` causes the second to supersede the first. When attempting to install on a totally clean system (no ports installed), cc65 is not installed, and the build fails: https://gist.github.com/lafiosca/78c4d91a84f1233599265654e2831da7#file-stdout

(You can see that the Portfile I used in that gist was modified to point at @bodgit's branch.)

Locally I changed the Portfile slightly to have a single line for the build dependencies:
```
depends_build       port:cc65 port:pkgconfig
```

It appears this allowed it to run and build successfully: https://gist.github.com/lafiosca/be6c80f760a00583076d56dc809a88b0

I haven't tested it yet with my real hardware, but I also don't have 100%-known-good hardware. I will try it out and let y'all know.

**Comment by bodgit** [comment]
Ah, it's a missing a `\` on the end of the first line.

**Comment by bodgit** [comment]
@lafiosca I've updated the PR, please re-test if you can.

**Comment by lafiosca** [comment]
Looks like that did the trick, @bodgit. I'm now going to see if I can actually read from my 1541 via the ZoomFloppy. (I haven't used one of these before, so if there are any tips now is the time to share!)

**Comment by spiro-trikaliotis** [comment]
It is.
So, is this PR ready to be merged?

**Comment by bodgit** [comment]
@spiro-trikaliotis I believe so, if you're happy with the changes.

**Comment by lafiosca** [comment]
Looks good to me.
